version: 2

project_name: apt-proxy

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      flags:
        - -trimpath
      ldflags:
        - -s -w
        - -X "main.version={{ .Version }}"
        - -X "main.commit={{ .FullCommit }}"
        - -X "main.date={{ .Date }}"
      main: ./cmd/apt-proxy
      mod_timestamp: '{{ .CommitTimestamp }}'
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: ["386", arm, amd64, arm64]
    goarm:
      - "7"
      - "6"

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

nfpms:
  - id: packages
    package_name: apt-proxy
    vendor: soulteary
    homepage: https://github.com/soulteary/apt-proxy
    maintainer: soulteary <soulteary@gmail.com>
    description: Caching HTTP proxy for APT/YUM/Alpine package mirrors.
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/apt-proxy/LICENSE
        file_info:
          mode: 0644

dockers:
  - image_templates:
      - "soulteary/apt-proxy:linux-amd64-{{ .Tag }}"
      - "soulteary/apt-proxy:linux-amd64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/apt-proxy"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/apt-proxy"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  - image_templates:
      - "soulteary/apt-proxy:linux-arm64-{{ .Tag }}"
      - "soulteary/apt-proxy:linux-arm64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm64
    goarm: ''
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/apt-proxy"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/apt-proxy"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  - image_templates:
      - "soulteary/apt-proxy:linux-armv7-{{ .Tag }}"
      - "soulteary/apt-proxy:linux-armv7"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/apt-proxy"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/apt-proxy"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

docker_manifests:
  - name_template: "soulteary/apt-proxy:{{ .Tag }}"
    image_templates:
      - "soulteary/apt-proxy:linux-amd64-{{ .Tag }}"
      - "soulteary/apt-proxy:linux-arm64-{{ .Tag }}"
      - "soulteary/apt-proxy:linux-armv7-{{ .Tag }}"

  - name_template: "soulteary/apt-proxy:latest"
    image_templates:
      - "soulteary/apt-proxy:linux-amd64-{{ .Tag }}"
      - "soulteary/apt-proxy:linux-arm64-{{ .Tag }}"
      - "soulteary/apt-proxy:linux-armv7-{{ .Tag }}"

release:
  github:
    owner: soulteary
    name: apt-proxy
  draft: false
  prerelease: auto
  mode: append
