name: "Security Scan"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 00:00 on Sunday UTC time.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'tests/**'
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

env:
  GO_VERSION: "1.27.0"

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Security Scan
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@v2.28.0
          gosec -fmt sarif -out results.sarif ./...

      - name: Temp sarif workaround
        if: always()
        shell: bash
        run: |
          sed -i "/null/d" results.sarif

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        with:
          sarif_file: results.sarif
